export DOTFILES=~/source/dotfiles

# Enable menu driven completion
zstyle ':completion:*' menu select
# Enable case-insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
# Enable autocompletion for SSH hosts and logins
zstyle ':completion:*:ssh:*' hosts
zstyle ':completion:*:slogin:*' hosts

# Set up fzf
source /usr/share/doc/fzf/examples/key-bindings.zsh
source /usr/share/doc/fzf/examples/completion.zsh

# Set up ls colors
export LS_COLORS="$(vivid generate molokai)"

### Zplugin configuration
###

# Zplugin setup
source ~/.zinit/bin/zinit.zsh

# Autosuggestions & fast-syntax-highlighting
zinit ice wait lucid atinit"ZINIT[COMPINIT_OPTS]=-C; zpcompinit; zpcdreplay"
zinit light zdharma/fast-syntax-highlighting

# zsh-autosuggestions
zinit ice wait lucid atload"!_zsh_autosuggest_start"
zinit light zsh-users/zsh-autosuggestions

# zsh-completions
zinit ice wait lucid blockf atpull"zinit creinstall -q ."
zinit light zsh-users/zsh-completions

# sharkdp/bat
zinit ice as"command" from"gh-r" mv"bat* -> bat" pick"bat/bat"
zinit light sharkdp/bat

# ogham/exa, replacement for ls
zinit ice wait lucid from"gh-r" as"program" mv"bin/exa* -> exa"
zinit light ogham/exa

# set exa aliases
zinit light DarrinTisdale/zsh-aliases-exa

# sharkdp/fd
zinit ice as"program" from"gh-r" mv"fd* -> fd" pick"fd/fd"
zinit light sharkdp/fd

# BurntSushi/ripgrep
zinit ice as"program" from"gh-r" mv"ripgrep* -> rg" pick "rg/rg"
zinit light BurntSushi/ripgrep

# sorin-ionescu/prezto/modules/history
zinit ice svn
zinit snippet PZT::modules/history

# sorin-ionescu/prezto/modules/git
zinit ice svn
zinit snippet PZT::modules/git

# zdharma/history-search-multi-word
zstyle ":history-search-multi-word" page-size "11"
zinit ice wait lucid
zinit light zdharma/history-search-multi-word

# set prompt theme
zinit ice from="gh-r" as"program" atload'eval "$(starship init zsh)"'
zinit load starship/starship

# ryutok/rust-zsh-completions
zinit light ryutok/rust-zsh-completions

# esc/conda-zsh-completions
zinit light esc/conda-zsh-completion

### End zplugin configuration
###

# Enable completion
autoload -Uz compinit
compinit

### Functions
###

# Load identities
function load-identities() {
	 zstyle ':prezto:module:ssh:load' identities 'id_nevin_github'
	 zinit ice svn
	 zinit snippet PZT::modules/ssh
}

# Source ROS Noetic
function source-ros-noetic() {
	 source /opt/ros/noetic/setup.zsh
}

# Source ROS Foxy
function source-ros-foxy() {
	 source /opt/ros/foxy/setup.zsh
}

### End functions
###

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/nevin/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/nevin/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/nevin/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/nevin/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Misc
alias open=xdg-open

# Configure junegunn/fzf
#
# Use ~~ as the trigger sequence instead of the default **
export FZF_COMPLETION_TRIGGER='~~'

# Options to fzf command
export FZF_COMPLETION_OPTS='--border --info=inline'

# Use fd (https://github.com/sharkdp/fd) instead of the default find
# command for listing path candidates.
# - The first argument to the function ($1) is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
  fd --hidden --follow --exclude ".git" . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude ".git" . "$1"
}

# (EXPERIMENTAL) Advanced customization of fzf options via _fzf_comprun function
# - The first argument to the function is the name of the command.
# - You should make sure to pass the rest of the arguments to fzf.
_fzf_comprun() {
  local command=$1
  shift

  case "$command" in
    cd)           fzf "$@" --preview 'tree -C {} | head -200' ;;
    export|unset) fzf "$@" --preview "eval 'echo \$'{}" ;;
    ssh)          fzf "$@" --preview 'dig {}' ;;
    *)            fzf "$@" ;;
  esac
}
# End configure junegunn/fzf

# Source aliases
source aliases.zsh
